URL_SERVICE = "https://9361255b-2b03-4558-844a-a7aac4a10efb.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/procducts/kits/"
CREATE_USER_PATH = "/api/v1/users/"